name: lavender_seed
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/gliscowo/lavender_seed

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
